# Generated by Django 3.1.7 on 2021-03-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedplay',
            name='artist',
            field=models.OneToOneField(default='DEFAULT VALUE', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='items.artist'),
        ),
    ]
