# Generated by Django 3.1.7 on 2021-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id_art',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='id_item',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
