# Generated by Django 3.1.7 on 2021-03-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name_item',
            new_name='traname',
        ),
        migrations.AddField(
            model_name='artist',
            name='artid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='traid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
