# Generated by Django 3.1.7 on 2021-03-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210301_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='id_art',
            new_name='artist',
        ),
    ]
