# Generated by Django 3.1.7 on 2021-03-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210301_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture_art',
            old_name='id_art',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='picture_item',
            old_name='id_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tx_item',
            old_name='id_art',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='tx_item',
            old_name='id_item',
            new_name='item',
        ),
    ]
