# Generated by Django 3.1.7 on 2021-03-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210301_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='artist',
        ),
    ]
