# Generated by Django 3.1.7 on 2021-03-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210301_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='artist',
        ),
    ]
