# Generated by Django 3.1.7 on 2021-03-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_items_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='artist',
        ),
        migrations.AddField(
            model_name='items',
            name='artist',
            field=models.ManyToManyField(related_name='id_artista', to='items.Artist'),
        ),
    ]
