# Generated by Django 3.1.7 on 2021-03-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20210301_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='artist',
        ),
        migrations.AddField(
            model_name='items',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_artista', to='items.artist'),
            preserve_default=False,
        ),
    ]
