# Generated by Django 3.1.7 on 2021-03-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210302_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_art',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='items',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='tx_item',
            name='artist',
        ),
        migrations.AddField(
            model_name='items',
            name='name_art',
            field=models.CharField(blank=True, max_length=255, verbose_name='name_art'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Picture_art',
        ),
    ]
