# Generated by Django 3.1.7 on 2021-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20210302_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id_item',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
