# Generated by Django 3.1.7 on 2021-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210303_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='id_item',
            field=models.CharField(max_length=255),
        ),
    ]
