# Generated by Django 3.1.7 on 2021-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210303_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id_item',
        ),
    ]
