# Generated by Django 3.1.7 on 2021-03-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_items_id_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tx_item',
            old_name='item',
            new_name='item_pic',
        ),
    ]
