# Generated by Django 3.1.7 on 2021-02-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=255, verbose_name='age'),
        ),
    ]
